#!/usr/bin/env php
<?php

use App\Console\Commands\Command;
use DI\ContainerBuilder;
use Psr\Container\ContainerInterface;
use Ultra\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

require_once __DIR__ . '/vendor/autoload.php';

$env = (new ArgvInput())->getParameterOption(['--env', '-e'], 'dev');

if ($env) {
    $_ENV['APP_ENV'] = $env;
}

/** @var ContainerInterface $container */
$container = (new ContainerBuilder())
    ->addDefinitions(__DIR__ . '/config/container.php')
    ->build();
    
try {
    /** @var Application $application */
    $application = $container->get(Application::class);
    
    // Register your console commands here
    $application->add($container->get(Command::class));
    
    exit($application->run());
} catch (Throwable $exception) {
    echo $exception->getMessage();
    exit(1);
}